stages:
  - build
  - release
  - deploy

before_script:
  - docker info
  - echo $CI_PROJECT_NAME
  - echo $CI_COMMIT_REF_NAME
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - ssh-add <(echo "$MASTER_PRIVATE_KEY")

build:
  stage: build
  script:
    - docker build -t $CI_PROJECT_NAME .
    - docker tag $CI_PROJECT_NAME moneygames/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    
release:
  stage: release
  script:
    - docker push moneygames/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
    
deploy:
  stage: deploy
  only:
    - master
  script:
    - ssh root@142.93.11.143 'cd main && ./restart'
